apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: owl1p0q91-go 
  janus-idp.io/tekton: owl1p0q91-go
  backstage.io/kubernetes-id: owl1p0q91-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: owl1p0q91-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml