apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: owl1p0q91-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: owl1p0q91-go 
  name: owl1p0q91-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: owl1p0q91-go 
